name: Production workflow
run-name: Deploy site to production environment

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: "Install NodeJS"
      uses: actions/setup-node@v3.5.1
      with: 
        version: 18.x
    - name: "Checkout source code"
      uses: actions/checkout@v2.5.0
    - name: "Build website"
      run: |
        npm install
        npm run build
