name: Production workflow
run-name: Deploy site to production environment

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: "NodeJS Install"
       uses: actions/setup-node@v3.5.1
       with: 
        node-version: 18 
     - name: "Source Checkout"
       uses: actions/checkout@v2.5.0
     - name: "Dependencies Installation"
       run: npm install
     - name: "Code Testing"
       run: npm run test 
     - name: "Static Site Build"
       run: npm run build   
     - name: "Netlify Deployment"
       uses: nwtgck/actions-netlify@v1.2.4
       with: 
        publish-dir: 'public'
        production-branch: 'main'
        production-deploy: true
        fails-without-credentials: true
       env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
     